package io.college.cms.core.examination.model;

import java.time.LocalDate;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import io.college.cms.core.application.LocalDateConverter;
import io.college.cms.core.dynamodb.constants.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = Table.EXAM_SUBJECT_TIME_TABLE)
public class TimeTableModel {
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	private String hashKey;
	private String examName;
	private String courseName;
	private String semester;
	private String subject;
	@DynamoDBTypeConverted(converter = LocalDateConverter.class)
	private LocalDate startTime;
	@DynamoDBTypeConverted(converter = LocalDateConverter.class)
	private LocalDate endTime;
	private String subjectType;
	private String additionalInformation;
}
