package io.college.cms.core.announcement.model;

import java.time.LocalDate;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import io.college.cms.core.dynamodb.constants.Table;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@DynamoDBTable(tableName = Table.ANNOUNCEMENT_TABLE)
public class AnnouncementModel {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String announcementKey;
	@DynamoDBAttribute
	private boolean sendToAll;
	@DynamoDBAttribute
	private String courseName;
	@DynamoDBAttribute
	private String subject;
	@DynamoDBAttribute
	private String description;
	@DynamoDBAttribute
	private LocalDate scheduleDate;

}
