package io.college.cms.core.announcement.model;

import java.time.LocalDate;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import io.college.cms.core.application.LocalDateConverter;
import io.college.cms.core.dynamodb.constants.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = Table.ANNOUNCEMENT_TABLE)
public class AnnouncementModel {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String announcementKey;
	@DynamoDBAttribute
	private boolean sendToAll;
	@DynamoDBAttribute
	private String courseName;
	@DynamoDBAttribute
	private String subject;
	@DynamoDBAttribute
	private String description;
	@DynamoDBTypeConverted(converter = LocalDateConverter.class)
	private LocalDate scheduleDate;
}
