package io.college.cms.core.ui.services;

public class MenuConstants {
	static final String ANNOUNCEMENT = "Announcement";
	static final String PUBLISH_ANNOUNCEMENT = "Publish Announcement";
	static final String VIEW_ALL_ANNOUNCEMENT = "View All Announcements";
	static final String USER = "User";
	static final String VIEW_ALL_USER = "View users";
	static final String ADD_USER = "Add user";
	static final String MY_PROFILE = "My profile";
	static final String UPLOAD_DOCUMENTS = "Upload document";
	static final String VIEW_ALL_DOCUMENTS = "View User documents";
	static final String MY_DOCUMENTS = "My documents";
	static final String MY_NOTIFICATIONS = "My notifications";
	static final String RESULTS = "Results";
	static final String VIEW_RESULTS = "View results";
	static final String FAQ_BOT = "FAQ Bot";
	static final String ADMISSION = "Admission";
	static final String OPEN_ADMISSIONS = "Open Admissions";
	static final String CONFIGURE_ADMISSIONS = "Configure Admissions";
	static final String ADMISSION_REQUEST_QUEUE = "Admission request queue";
	static final String APPLY_ADMISSIONS = "Apply Admissions";
	static final String FEES = "Fees";
	static final String FEES_QUEUE = "fees queue";
	static final String EXAMS = "Exams";
	static final String VIEW_ALL_EXAMS = "View all exams";
	static final String SCHEDULE_EXAM = "Schedule Exam";
	static final String VIEW_EXAM_TIMETABLE = "View exam timetable";
	static final String DOWNLOAD_QR_FOR_EXAMS = "Download qr for exams";
	static final String COURSES = "Courses";
	static final String VIEW_ALL_COURSES = "View all courses";
	static final String NEW_COURSE = "New course";
	static final String CONFIGURE_NOTIFICATIONS = "Configure Notifications";
	static final String JOB = "Jobs";
	static final String PUBLISH_JOB = "Publish job";
	static final String VIEW_ALL_JOBS = "View Jobs";
	static final String CONFIGURE_FEES = "Configure Fees";
	static final String PUBLISH_FEES = "Fees details";
	static final String USER_GROUP = "User Group";
	static final String ADD_TO_GROUP = "Add to Group";
	static final String SCHEDULE_TIME_SUBJECTS = "Schedule time for subjects";
	static final String ATTENDANCE = "Attendance";
	static final String TAG_ATTENDANCE = "Tag Attendance";
	static final String VIEW_ATTENDANCE = "View Attendance";
}